services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - stone-network
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: "redis:alpine"
    container_name: stone-guide-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - stone-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=5001
    container_name: stone-guide-backend
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      - redis
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - stone-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 5
    secrets:
     - mongo_uri
     - redis_host
     - redis_port

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: stone-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - stone-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 5

  ai-module:
    build:
      context: ./ai-module
    container_name: stone-guide-ai
    restart: always
    ports:
      - "5002:5002"
    volumes:
      - ./ai-module:/app
    networks:
      - stone-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/ai-stone-recognition"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  mongo-data:
  keycloak-data:

networks:
  stone-network:
    driver: bridge

secrets:
  mongo_uri:
    file: ./secrets/mongo_uri.txt
  redis_host:
    file: ./secrets/redis_host.txt
  redis_port:
    file: ./secrets/redis_port.txt