version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - stone-network

  redis:
    image: "redis:alpine"
    container_name: stone-guide-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - stone-network

  backend:
    build: .
    container_name: stone-guide-backend
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    volumes:
      - ./src:/backend/src
      - /backend/node_modules
    networks:
      - stone-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: stone-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    networks:
      - stone-network

volumes:
  mongo-data:
  keycloak-data:

networks:
  stone-network:
    driver: bridge
