version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: stone-guide-backend
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./src:/backend/src
      - /backend/node_modules

volumes:
  mongo-data:
