apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: qlpak/stone-guide-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          command: ["npm", "run", "dev"]
          workingDir: /app
          envFrom:
            - secretRef:
                name: frontend-secrets
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
