apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-module
  labels:
    app: ai-module
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-module
  template:
    metadata:
      labels:
        app: ai-module
    spec:
      containers:
        - name: ai-module
          image: qlpak/stone-guide-ai:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
          readinessProbe:
            httpGet:
              path: /ai/predict
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ai/predict
              port: 5002
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              memory: "384Mi"
              cpu: "200m"
            limits:
              memory: "768Mi"
              cpu: "350m"
